import Head from "next/head";
import { FC } from "react";
import { GetServerSideProps } from "next";
import { wrapper } from "../store";
import Form from "../components/UI/Form";
import Header from "../components/Header";
import Title from "../components/Title";
import About from "../components/About";
import Technologies from "../components/Technologies";
import Steps from "../components/Steps";
import Questions from "../components/Questions";
import Review from "../components/Review";
import Gallery from "../components/Gallery";
import Footer from "../components/Footer";

export const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Webtronics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Header />
        <main className="main">
          <Title />
          <About />
          <Technologies />
          <Steps />
          <Questions />
          <Review />
          <Gallery />
          <Form />
        </main>
      </div>
      <Footer />
    </>
  );
};

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (context) => {
    return { props: [] };
  });

export default Home;
